spring:

  jackson:
    property-naming-strategy: SNAKE_CASE

  config:
    import: "aws-parameterstore:/config/dawn-cs-study/"

  profiles:
    active: prod
    group:
      prod: s3-prod

  ai:
    openai:
      api-key: ${open-ai-api-key}
      embedding:
        options:
          model: text-embedding-3-large  # or text-embedding-3-small (1536??)

  datasource:
    url: ${db_url}
    username: ${db_user}
    password: ${db_password}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace