bootJar { enabled = true }

ext {
    set('springAiVersion', "1.0.1")
}

dependencyManagement {
    imports {
        mavenBom "org.springframework.ai:spring-ai-bom:${springAiVersion}"
    }
}

dependencies {

    // spring ai
    implementation 'org.springframework.ai:spring-ai-starter-vector-store-pgvector'
    implementation 'org.springframework.ai:spring-ai-advisors-vector-store'
    implementation 'org.springframework.ai:spring-ai-starter-model-openai'

    // JPA , PostgreSQL
    implementation("org.springframework.boot:spring-boot-starter-data-jpa")
    runtimeOnly 'org.postgresql:postgresql'
    // flexMark
    implementation 'com.vladsch.flexmark:flexmark-all:0.64.8'

}


tasks.register('buildMdSyncZip', Zip) {
    from compileJava
    from processResources
    into('lib') {
        from configurations.runtimeClasspath
    }
}